// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelUpload():Promise<void>;

export function ClearAudit(arg1:boolean):Promise<void>;

export function ConfirmUpload():Promise<main.UploadResult>;

export function ConnectAndDiscover(arg1:main.TestInput):Promise<main.ConnectDiscoverResult>;

export function CreateNote(arg1:main.NoteInput):Promise<number>;

export function CreateProject(arg1:main.ProjectInput):Promise<number>;

export function CreateRemoteFile(arg1:main.FileOpInput):Promise<void>;

export function CreateServer(arg1:main.ServerInput):Promise<number>;

export function DeleteFile(arg1:main.FileOpInput):Promise<void>;

export function DeleteNote(arg1:number,arg2:boolean):Promise<void>;

export function DeleteProject(arg1:number,arg2:boolean):Promise<void>;

export function DeleteSavedPath(arg1:number,arg2:boolean):Promise<void>;

export function DeleteServer(arg1:number,arg2:boolean):Promise<void>;

export function DisconnectServer(arg1:number):Promise<void>;

export function DiscoverProjects(arg1:number):Promise<Array<main.Project>>;

export function DownloadFile(arg1:number,arg2:string):Promise<void>;

export function ListAllNotes():Promise<Array<main.Note>>;

export function ListAudit():Promise<Array<main.Audit>>;

export function ListFiles(arg1:number,arg2:string):Promise<main.FileListResult>;

export function ListNotes(arg1:number):Promise<Array<main.Note>>;

export function ListProjects(arg1:number):Promise<Array<main.Project>>;

export function ListQuickCommands(arg1:number):Promise<Array<main.QuickCommand>>;

export function ListSavedPaths(arg1:number,arg2:number):Promise<Array<main.SavedPath>>;

export function ListServers():Promise<Array<main.Server>>;

export function Meta():Promise<main.Meta>;

export function Mkdir(arg1:main.FileOpInput):Promise<void>;

export function ParseSSHCommand(arg1:string):Promise<main.ParsedSSH>;

export function ReadFile(arg1:number,arg2:string):Promise<main.FileContent>;

export function RemovePathTest(arg1:number,arg2:string):Promise<void>;

export function RenameFile(arg1:main.FileOpInput):Promise<void>;

export function RunQuickCommand(arg1:number,arg2:string,arg3:boolean):Promise<main.CommandResult>;

export function SaveRemotePath(arg1:main.SavePathInput):Promise<number>;

export function SetActivePath(arg1:number,arg2:string):Promise<string>;

export function StageUploadFile(arg1:number,arg2:string):Promise<main.UploadPreview>;

export function StageUploadFolder(arg1:number,arg2:string):Promise<main.UploadPreview>;

export function StageUploadZip(arg1:number,arg2:string):Promise<main.UploadPreview>;

export function StartTerminal(arg1:number,arg2:number,arg3:number):Promise<string>;

export function StopTerminal(arg1:string):Promise<void>;

export function TerminalInput(arg1:string,arg2:string):Promise<void>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TestConnection(arg1:main.TestInput):Promise<main.TestResult>;

export function TestPath(arg1:number,arg2:string):Promise<main.PathTestResult>;

export function UpdateNote(arg1:number,arg2:main.NoteInput):Promise<void>;

export function UpdateProject(arg1:number,arg2:main.ProjectInput):Promise<void>;

export function UpdateServer(arg1:number,arg2:main.ServerInput):Promise<void>;

export function WriteFile(arg1:main.FileWriteInput):Promise<void>;
