// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelUpload() {
  return window['go']['main']['App']['CancelUpload']();
}

export function ClearAudit(arg1) {
  return window['go']['main']['App']['ClearAudit'](arg1);
}

export function ConfirmUpload() {
  return window['go']['main']['App']['ConfirmUpload']();
}

export function ConnectAndDiscover(arg1) {
  return window['go']['main']['App']['ConnectAndDiscover'](arg1);
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateRemoteFile(arg1) {
  return window['go']['main']['App']['CreateRemoteFile'](arg1);
}

export function CreateServer(arg1) {
  return window['go']['main']['App']['CreateServer'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteNote(arg1, arg2) {
  return window['go']['main']['App']['DeleteNote'](arg1, arg2);
}

export function DeleteProject(arg1, arg2) {
  return window['go']['main']['App']['DeleteProject'](arg1, arg2);
}

export function DeleteSavedPath(arg1, arg2) {
  return window['go']['main']['App']['DeleteSavedPath'](arg1, arg2);
}

export function DeleteServer(arg1, arg2) {
  return window['go']['main']['App']['DeleteServer'](arg1, arg2);
}

export function DisconnectServer(arg1) {
  return window['go']['main']['App']['DisconnectServer'](arg1);
}

export function DiscoverProjects(arg1) {
  return window['go']['main']['App']['DiscoverProjects'](arg1);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function ListAllNotes() {
  return window['go']['main']['App']['ListAllNotes']();
}

export function ListAudit() {
  return window['go']['main']['App']['ListAudit']();
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function ListNotes(arg1) {
  return window['go']['main']['App']['ListNotes'](arg1);
}

export function ListProjects(arg1) {
  return window['go']['main']['App']['ListProjects'](arg1);
}

export function ListQuickCommands(arg1) {
  return window['go']['main']['App']['ListQuickCommands'](arg1);
}

export function ListSavedPaths(arg1, arg2) {
  return window['go']['main']['App']['ListSavedPaths'](arg1, arg2);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function Meta() {
  return window['go']['main']['App']['Meta']();
}

export function Mkdir(arg1) {
  return window['go']['main']['App']['Mkdir'](arg1);
}

export function ParseSSHCommand(arg1) {
  return window['go']['main']['App']['ParseSSHCommand'](arg1);
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['App']['ReadFile'](arg1, arg2);
}

export function RemovePathTest(arg1, arg2) {
  return window['go']['main']['App']['RemovePathTest'](arg1, arg2);
}

export function RenameFile(arg1) {
  return window['go']['main']['App']['RenameFile'](arg1);
}

export function RunQuickCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunQuickCommand'](arg1, arg2, arg3);
}

export function SaveRemotePath(arg1) {
  return window['go']['main']['App']['SaveRemotePath'](arg1);
}

export function SetActivePath(arg1, arg2) {
  return window['go']['main']['App']['SetActivePath'](arg1, arg2);
}

export function StageUploadFile(arg1, arg2) {
  return window['go']['main']['App']['StageUploadFile'](arg1, arg2);
}

export function StageUploadFolder(arg1, arg2) {
  return window['go']['main']['App']['StageUploadFolder'](arg1, arg2);
}

export function StageUploadZip(arg1, arg2) {
  return window['go']['main']['App']['StageUploadZip'](arg1, arg2);
}

export function StartTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartTerminal'](arg1, arg2, arg3);
}

export function StopTerminal(arg1) {
  return window['go']['main']['App']['StopTerminal'](arg1);
}

export function TerminalInput(arg1, arg2) {
  return window['go']['main']['App']['TerminalInput'](arg1, arg2);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TestPath(arg1, arg2) {
  return window['go']['main']['App']['TestPath'](arg1, arg2);
}

export function UpdateNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2);
}

export function UpdateServer(arg1, arg2) {
  return window['go']['main']['App']['UpdateServer'](arg1, arg2);
}

export function WriteFile(arg1) {
  return window['go']['main']['App']['WriteFile'](arg1);
}
