// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAudit(arg1) {
  return window['go']['main']['App']['ClearAudit'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateRemoteFile(arg1) {
  return window['go']['main']['App']['CreateRemoteFile'](arg1);
}

export function CreateServer(arg1) {
  return window['go']['main']['App']['CreateServer'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteProject(arg1, arg2) {
  return window['go']['main']['App']['DeleteProject'](arg1, arg2);
}

export function DeleteServer(arg1, arg2) {
  return window['go']['main']['App']['DeleteServer'](arg1, arg2);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function ListAudit() {
  return window['go']['main']['App']['ListAudit']();
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function ListProjects(arg1) {
  return window['go']['main']['App']['ListProjects'](arg1);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function Meta() {
  return window['go']['main']['App']['Meta']();
}

export function Mkdir(arg1) {
  return window['go']['main']['App']['Mkdir'](arg1);
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['App']['ReadFile'](arg1, arg2);
}

export function RenameFile(arg1) {
  return window['go']['main']['App']['RenameFile'](arg1);
}

export function StartTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartTerminal'](arg1, arg2, arg3);
}

export function StopTerminal(arg1) {
  return window['go']['main']['App']['StopTerminal'](arg1);
}

export function TerminalInput(arg1, arg2) {
  return window['go']['main']['App']['TerminalInput'](arg1, arg2);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2);
}

export function UpdateServer(arg1, arg2) {
  return window['go']['main']['App']['UpdateServer'](arg1, arg2);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}

export function WriteFile(arg1) {
  return window['go']['main']['App']['WriteFile'](arg1);
}
