// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearAudit(arg1:boolean):Promise<void>;

export function CreateProject(arg1:main.ProjectInput):Promise<number>;

export function CreateRemoteFile(arg1:main.FileOpInput):Promise<void>;

export function CreateServer(arg1:main.ServerInput):Promise<number>;

export function DeleteFile(arg1:main.FileOpInput):Promise<void>;

export function DeleteProject(arg1:number,arg2:boolean):Promise<void>;

export function DeleteServer(arg1:number,arg2:boolean):Promise<void>;

export function DownloadFile(arg1:number,arg2:string):Promise<void>;

export function ListAudit():Promise<Array<main.Audit>>;

export function ListFiles(arg1:number,arg2:string):Promise<main.FileListResult>;

export function ListProjects(arg1:number):Promise<Array<main.Project>>;

export function ListServers():Promise<Array<main.Server>>;

export function Meta():Promise<main.Meta>;

export function Mkdir(arg1:main.FileOpInput):Promise<void>;

export function ReadFile(arg1:number,arg2:string):Promise<main.FileContent>;

export function RenameFile(arg1:main.FileOpInput):Promise<void>;

export function StartTerminal(arg1:number,arg2:number,arg3:number):Promise<string>;

export function StopTerminal(arg1:string):Promise<void>;

export function TerminalInput(arg1:string,arg2:string):Promise<void>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TestConnection(arg1:main.TestInput):Promise<main.TestResult>;

export function UpdateProject(arg1:number,arg2:main.ProjectInput):Promise<void>;

export function UpdateServer(arg1:number,arg2:main.ServerInput):Promise<void>;

export function UploadFile(arg1:number,arg2:string):Promise<void>;

export function WriteFile(arg1:main.FileWriteInput):Promise<void>;
